name: Dummy workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.8
      # - uses: actions/cache@v2
      #   with:
      #     path: ~/.cache/pip
      #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pip-
      # - run: pip install -r requirements.txt
      # - run: pytest
      # - run: ${{ github.event }}
      # - run: echo ${{ github.event.base_ref }}
      # - run: echo ${{ github.event.head_ref }}
      # - run: echo ${{ github.event.before }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/setup-java@v1
        with:
          java-version: 17
          distribution: 'corrretto'
      - uses: actions/checkout@v4
      - name: Run Designite Java
      - script: 
          - java --version
          - ls -a
          - mkdir -p /tmp/Desingnite_Output_${{ github.sha }}
          - ls -a /tmp/
        run: java -jar ./.github/DesigniteJava.jar -i ./ -o /tmp/Desingnite_Output_${{ github.sha }} -d
      
